default_platform(:ios)
platform :ios do
  lane :upload_to_app_store_connect do
    ENV["SPACESHIP_LOGGER"] = "nil"
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_KEY_CONTENT"],
      is_key_content_base64: true
    )
   deliver(
    ipa: "./app-ipa/math_joy_practice_english.ipa",
    skip_screenshots: true,
    skip_metadata: true,
    skip_app_version_update: true,
    force: true,
    run_precheck_before_submit: false
   )
  end
end