name: Build Flutter iOS IPA1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'

      - name: Install envsubst
        run: |
          brew install gettext
          brew link --force gettext

      - name: Generate ExportOptions.plist
        env:
          EXPORT_METHOD: app-store
          TEAM_ID: ${{ secrets.TEAM_ID }}
          APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER }}
          PROVISIONING_PROFILE_NAME: "My MathEnglish App App Store Distribution"
        run: |
          envsubst < ios/ExportOptions-Template.plist > ios/ExportOptions.plist

      - name: Create temporary keychain
        env:
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          KEYCHAIN_PATH="$RUNNER_TEMP/temp.keychain-db"
          security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
          security set-keychain-settings -lut 21600 "$KEYCHAIN_PATH"
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
          security default-keychain -s "$KEYCHAIN_PATH"
          security list-keychains -s "$KEYCHAIN_PATH" $(security list-keychains | sed s/\"//g)

      - name: Import Apple certificate into keychain
        env:
          IOS_CERTIFICATE_PASSWORD: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
          IOS_CERTIFICATE_BASE64: ${{ secrets.IOS_CERTIFICATE_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          KEYCHAIN_PATH="$RUNNER_TEMP/temp.keychain-db"
          CERTIFICATE_PATH="$RUNNER_TEMP/certificate.p12"

          # Decode and verify certificate
          echo "$IOS_CERTIFICATE_BASE64" | base64 --decode > "$CERTIFICATE_PATH"
          ls -l "$CERTIFICATE_PATH"  # Debug: Verify file
          file "$CERTIFICATE_PATH"   # Debug: Check file type
          echo "Certificate size: $(stat -f %z "$CERTIFICATE_PATH") bytes"  # Debug: Size

          # Import with explicit PKCS12 format
          security import "$CERTIFICATE_PATH" -k "$KEYCHAIN_PATH" -P "$IOS_CERTIFICATE_PASSWORD" -A -T /usr/bin/codesign -f pkcs12

          # Debug: Verify certificate import
          security find-identity -v -p codesigning "$KEYCHAIN_PATH"

          # Set key partition list
          security set-key-partition-list -S apple-tool:,apple: -s -k "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"

          # Unlock keychain
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"

      - name: Install provisioning profile
        env:
          IOS_PROVISIONING_PROFILE_BASE64: ${{ secrets.IOS_PROVISIONING_PROFILE_BASE64 }}
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          PROFILE_PATH=~/Library/MobileDevice/Provisioning\ Profiles/profile.mobileprovision
          echo "$IOS_PROVISIONING_PROFILE_BASE64" | base64 --decode > "$PROFILE_PATH"
          ls -l "$PROFILE_PATH"  # Debug: Verify file

      - name: Install CocoaPods dependencies
        run: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Build IPA
        run: flutter build ipa --release --export-options-plist=ios/ExportOptions.plist

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: build/ios/ipa/*.ipa
