name: Build iOS IPA
on: push  # Trigger on code push

jobs:
  build:
    runs-on: macos-latest  # Required for iOS builds
    steps:
      # 1. Checkout code
      - uses: actions/checkout@v4

      # 2. Set up Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'  # Or your Flutter version

      # 3. Install CocoaPods and dependencies
      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          pod setup

      # 4. Get Flutter dependencies and run `pod install`
      - name: Install dependencies
        run: |
          flutter pub get
          cd ios
          pod install --repo-update  # Generates Pods folder
          cd ..

      # 5. Build the IPA
      - name: Build IPA
        run: flutter build ipa --release --no-codesign

      # 6. Upload the IPA as an artifact
      - uses: actions/upload-artifact@v3
        with:
          name: app-release.ipa
          path: build/ios/ipa/*.ipa
