name: Build Flutter iOS IPA

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          channel: 'stable'

      - name: Install envsubst (for placeholder substitution)
        run: |
          brew install gettext
          brew link --force gettext

      - name: Decode and save iOS certificate (.p12)
        run: |
          echo "${{ secrets.IOS_CERTIFICATE_BASE64 }}" | base64 --decode > ios/ios_distribution.p12

      - name: Decode and save provisioning profile
        run: |
          echo "${{ secrets.IOS_PROVISIONING_PROFILE_BASE64 }}" | base64 --decode > ios/profile.mobileprovision

      - name: Generate ExportOptions.plist
        env:
          EXPORT_METHOD: app-store
          TEAM_ID: ${{ secrets.TEAM_ID }}
          APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER }}
          PROVISIONING_PROFILE_NAME: "Your Provisioning Profile Name"  # Replace with your actual profile name
        run: |
          envsubst < ios/ExportOptions-Template.plist > ios/ExportOptions.plist

      - name: Set up Flutter dependencies
        run: flutter pub get

      - name: Install CocoaPods dependencies
        run: |
          cd ios
          pod install

      - name: Build IPA
        run: flutter build ipa --release --export-options-plist=ios/ExportOptions.plist

      # Optional: Upload IPA as artifact
      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: build/ios/ipa/*.ipa

