name: Build Flutter iOS IPA 26
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          channel: 'stable'
      - name: Install envsubst
        run: |
          brew install gettext
          brew link --force gettext
      - name: Generate ExportOptions.plist
        env:
          EXPORT_METHOD: app-store
          TEAM_ID: AHVM2Z8TDL
          APP_IDENTIFIER: com.tech4dev.mathJoyPracticeEnglish
          PROVISIONING_PROFILE_NAME: "My MathEnglish App App Store Distribution"
        run: |
          envsubst < ios/ExportOptions-Template.plist > ios/ExportOptions.plist
          cat ios/ExportOptions.plist
      - name: Create temporary keychain
        env:
          KEYCHAIN_PASSWORD: tempkeychainpassword
        run: |
          security create-keychain -p "$KEYCHAIN_PASSWORD" "$RUNNER_TEMP/temp.keychain-db"
          security set-keychain-settings -lut 21600 "$RUNNER_TEMP/temp.keychain-db"
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$RUNNER_TEMP/temp.keychain-db"
          security default-keychain -s "$RUNNER_TEMP/temp.keychain-db"
          security list-keychains -d user -s "$RUNNER_TEMP/temp.keychain-db"
          security show-keychain-info "$RUNNER_TEMP/temp.keychain-db"
      - name: Import Apple certificate into keychain
        env:
          IOS_CERTIFICATE_PASSWORD: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
          IOS_CERTIFICATE_BASE64: ${{ secrets.IOS_CERTIFICATE_BASE64 }}
          KEYCHAIN_PASSWORD: tempkeychainpassword
        run: |
          echo "$IOS_CERTIFICATE_BASE64" | base64 --decode > certificate.p12
          ls -l certificate.p12
          security import certificate.p12 -k "$RUNNER_TEMP/temp.keychain-db" -P "$IOS_CERTIFICATE_PASSWORD" -T /usr/bin/codesign -T /usr/bin/security || exit 1
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" "$RUNNER_TEMP/temp.keychain-db" || exit 1
          security find-identity -v -p codesigning "$RUNNER_TEMP/temp.keychain-db" || exit 1
          security find-certificate -a -p "$RUNNER_TEMP/temp.keychain-db" > cert_details.txt
          echo "Certificate details:"
          cat cert_details.txt
          security find-certificate -a -c "Alireza Ehiaei" -Z "$RUNNER_TEMP/temp.keychain-db" || exit 1
      - name: Install provisioning profile
        env:
          IOS_PROVISIONING_PROFILE_BASE64: ${{ secrets.IOS_PROVISIONING_PROFILE_BASE64 }}
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo "$IOS_PROVISIONING_PROFILE_BASE64" | base64 --decode > profile.mobileprovision
          ls -l profile.mobileprovision
          UUID=$(grep UUID -A1 -a profile.mobileprovision | grep -io "[-A-Z0-9]\{36\}" || echo "UUID not found")
          echo "UUID: $UUID"
          if [ "$UUID" != "UUID not found" ]; then
            mv profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/$UUID.mobileprovision
            ls -l ~/Library/MobileDevice/Provisioning\ Profiles/
          else
            echo "Error: Failed to extract UUID from provisioning profile"
            exit 1
          fi
      - name: Verify certificate and provisioning profile
        run: |
          security find-identity -v -p codesigning "$RUNNER_TEMP/temp.keychain-db"
          security find-certificate -c "Alireza Ehiaei" -p "$RUNNER_TEMP/temp.keychain-db" || echo "Certificate not found"
          security cms -D -i ~/Library/MobileDevice/Provisioning\ Profiles/*.mobileprovision || echo "Failed to decode provisioning profile"
          echo "Checking project.pbxproj for code signing settings:"
          grep "CODE_SIGN_IDENTITY" ios/Runner.xcodeproj/project.pbxproj
          grep "CODE_SIGN_STYLE" ios/Runner.xcodeproj/project.pbxproj
          grep "PROVISIONING_PROFILE_SPECIFIER" ios/Runner.xcodeproj/project.pbxproj || echo "No PROVISIONING_PROFILE_SPECIFIER found"
          xcodebuild -showBuildSettings -workspace ios/Runner.xcworkspace -scheme Runner | grep -E "CODE_SIGN_IDENTITY|CODE_SIGN_STYLE|PROVISIONING_PROFILE_SPECIFIER"
      - name: Build IPA with explicit code signing
        run: |
          flutter build ipa --release --export-options-plist=ios/ExportOptions.plist --codesign --verbose \
            --dart-define=CODE_SIGN_IDENTITY="Apple Distribution: Alireza Ehiaei (AHVM2Z8TDL)" \
            --dart-define=CODE_SIGN_STYLE=Manual \
            --dart-define=PROVISIONING_PROFILE_SPECIFIER="My MathEnglish App App Store Distribution"
      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: build/ios/ipa/*.ipa
