name: Diagnose iOS IPA Build - Profile Resolution

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  diagnose_ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          channel: 'stable'

      - name: Create temporary keychain
        env:
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          security create-keychain -p "$KEYCHAIN_PASSWORD" "$RUNNER_TEMP/temp.keychain-db"
          security set-keychain-settings -lut 21600 "$RUNNER_TEMP/temp.keychain-db"
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$RUNNER_TEMP/temp.keychain-db"
          security default-keychain -s "$RUNNER_TEMP/temp.keychain-db"

      - name: Import Apple certificate
        env:
          IOS_CERTIFICATE_PASSWORD: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
          IOS_CERTIFICATE_BASE64: ${{ secrets.IOS_CERTIFICATE_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          echo "$IOS_CERTIFICATE_BASE64" | base64 --decode > certificate.p12
          security import certificate.p12 -k "$RUNNER_TEMP/temp.keychain-db" -P "$IOS_CERTIFICATE_PASSWORD" -A -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" "$RUNNER_TEMP/temp.keychain-db"
          security find-identity -v -p codesigning "$RUNNER_TEMP/temp.keychain-db"

      - name: Install provisioning profile with UUID
        env:
          IOS_PROVISIONING_PROFILE_BASE64: ${{ secrets.IOS_PROVISIONING_PROFILE_BASE64 }}
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo "$IOS_PROVISIONING_PROFILE_BASE64" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/8a1b1294-3776-43ca-96ea-92eede62d283.mobileprovision
          ls -l ~/Library/MobileDevice/Provisioning\ Profiles/
          security cms -D -i ~/Library/MobileDevice/Provisioning\ Profiles/8a1b1294-3776-43ca-96ea-92eede62d283.mobileprovision > profile_details.plist
          cat profile_details.plist | grep -A 1 "TeamIdentifier\|BundleIdentifier"

      - name: Remove CocoaPods include from Release.xcconfig
        run: |
          cd ios/Flutter
          sed -i '' '/#include "Pods\/Target Support Files\/Pods-Runner\/Pods-Runner.release.xcconfig"/d' Release.xcconfig
          cat Release.xcconfig

      - name: Verify Xcode build settings
        run: |
          cd ios
          xcodebuild -project Runner.xcodeproj -target Runner -configuration Release -showBuildSettings > build_settings.txt
          grep -E "PROVISIONING_PROFILE|PRODUCT_BUNDLE_IDENTIFIER|DEVELOPMENT_TEAM" build_settings.txt

      - name: Attempt to build IPA with verbose logging
        run: |
          flutter build ipa --release --export-options-plist=ios/ExportOptions.plist --verbose > build_log.txt 2>&1
        continue-on-error: true

      - name: Upload build logs
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            build_log.txt
            ios/build_settings.txt
            ~/Library/MobileDevice/Provisioning\ Profiles/profile_details.plist
